# Generated by Django 3.2.5 on 2022-08-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20220802_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='forum',
            new_name='ad',
        ),
    ]
